language: java
sudo: false
install: true

jdk:
  - openjdk8

script: ./travis.sh

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    urls:
      - secure: "HBvQZrZJoFTn4tEi41Cg+lXsIxS0y+i5DiMSoQGQIuXdNgbDcvguHTuj3FGQ9ELOJ5bB9YwBoL/sBSWiSrRM/ust4b8LxP7Ki27oZgmuOT6tUF6o90GROzmKhMqUxeBa6f/exLqRKiTjDLAgYvSPKS28B1GLAYZSYHw2IaVb+pk="
  on_start: always
